# Generated by Django 4.2 on 2025-06-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0003_cart_chatroom_company_order_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
