# Generated by Django 4.2 on 2025-07-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0004_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exp1.cart'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DelegateDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(max_length=255)),
                ('delivery_date', models.DateField(verbose_name='تاريخ التوصيل')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp1.order')),
            ],
        ),
    ]
