# Generated by Django 4.2 on 2025-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0005_alter_cartitem_cart_delegatedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatedelivery',
            name='delivery_area',
            field=models.CharField(choices=[('area1', 'المنطقة 1'), ('area2', 'المنطقة 2'), ('area3', 'المنطقة 3')], max_length=255),
        ),
    ]
