# Generated by Django 4.2 on 2025-07-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0006_alter_delegatedelivery_delivery_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatedelivery',
            name='delegate',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
