# # Generated by Django 4.2 on 2025-10-18 16:10

# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     dependencies = [
#         ('exp1', '0009_user_first_name_user_last_name'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='chatroom',
#             name='create',
#         ),
#         migrations.AddField(
#             model_name='chatroom',
#             name='created_at',
#             field=models.DateTimeField(auto_now_add=True, default=1),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='cart',
#             name='user',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='cartitem',
#             name='product',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='exp1.productdetail'),
#         ),
#         migrations.AlterField(
#             model_name='cartitem',
#             name='quantity',
#             field=models.PositiveIntegerField(default=1),
#         ),
#         migrations.AlterField(
#             model_name='chatroom',
#             name='user',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='order',
#             name='complete_at',
#             field=models.DateTimeField(blank=True, null=True),
#         ),
#         migrations.AlterField(
#             model_name='order',
#             name='owner',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='orderitem',
#             name='product',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='exp1.productdetail'),
#         ),
#     ]


# Generated by Django 4.2 on 2025-10-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0009_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='create',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='exp1.productdetail'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='exp1.productdetail'),
        ),
    ]
