# # Generated by Django 4.2 on 2025-10-18 17:34

# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion


# class Migration(migrations.Migration):

#     dependencies = [
#         ('exp1', '0011_alter_chatroom_created_at_alter_order_placed_at'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='chatroom',
#             name='created_at',
#         ),
#         migrations.AddField(
#             model_name='chatroom',
#             name='create',
#             field=models.DateField(auto_now_add=True, default=1),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='cart',
#             name='user',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='cartitem',
#             name='product',
#             field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='exp1.productdetail'),
#         ),
#         migrations.AlterField(
#             model_name='cartitem',
#             name='quantity',
#             field=models.IntegerField(default=1),
#         ),
#         migrations.AlterField(
#             model_name='chatroom',
#             name='user',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='order',
#             name='complete_at',
#             field=models.DateTimeField(null=True),
#         ),
#         migrations.AlterField(
#             model_name='order',
#             name='owner',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='order',
#             name='placed_at',
#             field=models.DateTimeField(auto_now_add=True),
#         ),
#         migrations.AlterField(
#             model_name='orderitem',
#             name='product',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp1.productdetail'),
#         ),
#     ]


# Generated by Django 4.2 on 2025-10-18 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0011_alter_chatroom_created_at_alter_order_placed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='create',
            field=models.DateField(auto_now_add=True, default=date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prod',
                to='exp1.productdetail',
                # يمكن إزالة default إذا كنت متأكد أن كل المنتج موجود مسبقًا
            ),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp1.productdetail'),
        ),
    ]
