# Generated by Django 4.2 on 2025-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0015_alter_book_author_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(default=2000),
        ),
    ]
