# Generated by Django 4.2 on 2025-10-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0016_book_publish_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
    ]
