# Generated by Django 4.2 on 2025-10-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0017_remove_book_publish_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A12', to='exp1.chapter')),
            ],
        ),
    ]
