# Generated by Django 4.2 on 2025-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp1', '0018_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
